blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/stepolan/marketing-repo-template/discussions
    about: For "how do I…" or "what do you think about…" questions, use Discussions.
